import type { Post, SocialItem, SiteSettings, Recipe } from './types';

/**
 * Sample content shown until Supabase is configured (and as a graceful
 * fallback). Uses local images already in /public/images. Admin content
 * replaces all of this once the database is connected.
 */
export const SAMPLE_POSTS: Post[] = [
  {
    id: 's1',
    slug: 'full-body-strength',
    type: 'video',
    category: 'training',
    title: { tr: 'Tüm Vücut Güç Antrenmanı', en: 'Full Body Strength Session' },
    excerpt: {
      tr: 'Haftada 3 gün uygulanabilen, eklem dostu tam vücut rutini.',
      en: 'A joint-friendly full-body routine you can run 3x a week.',
    },
    body: {
      tr: 'Bu antrenmanda büyük kas gruplarını hedefleyen bileşik hareketlere odaklanıyoruz...',
      en: 'In this session we focus on compound movements that target the big muscle groups...',
    },
    imageUrl: '/images/mustafa-2.jpg',
    videoUrl: 'https://www.youtube.com/embed/UBMk30rjy0o',
    socialUrl: null,
    featured: true,
    createdAt: '2026-06-10T09:00:00Z',
  },
  {
    id: 's2',
    slug: 'morning-routine',
    type: 'video',
    category: 'lifestyle',
    title: { tr: 'Sabah Rutini', en: 'Morning Routine' },
    excerpt: {
      tr: 'Güne daha enerjik başlamak için 10 dakikalık rutin.',
      en: 'A 10-minute routine to start the day with more energy.',
    },
    body: {
      tr: 'Sabahları enerjini yükseltmek için basit ama etkili adımlar...',
      en: 'Simple but effective steps to raise your energy in the morning...',
    },
    imageUrl: '/images/mustafa-1.jpg',
    videoUrl: 'https://www.youtube.com/embed/2vjPBrBU-TM',
    socialUrl: null,
    featured: true,
    createdAt: '2026-06-08T09:00:00Z',
  },
  {
    id: 's3',
    slug: 'eating-for-energy',
    type: 'blog',
    category: 'nutrition',
    title: { tr: 'Enerji İçin Beslenme', en: 'Eating for Energy' },
    excerpt: {
      tr: 'Gün boyu tok ve enerjik kalmanın pratik yolları.',
      en: 'Practical ways to stay full and energized all day.',
    },
    body: {
      tr: 'Protein, lif ve doğru karbonhidrat dengesi enerjinin anahtarı...',
      en: 'A balance of protein, fiber and the right carbs is the key to energy...',
    },
    imageUrl: '/images/mustafa-4.jpg',
    videoUrl: null,
    socialUrl: null,
    featured: false,
    createdAt: '2026-06-05T09:00:00Z',
  },
  {
    id: 's4',
    slug: 'discipline-over-motivation',
    type: 'blog',
    category: 'mindset',
    title: { tr: 'Disiplin, Motivasyondan Önce Gelir', en: 'Discipline Over Motivation' },
    excerpt: {
      tr: 'Motivasyon biter, disiplin kalır. Sistemini nasıl kurarsın?',
      en: 'Motivation fades, discipline stays. How to build your system.',
    },
    body: {
      tr: 'Küçük, tekrarlanabilir alışkanlıklar uzun vadede her şeyi değiştirir...',
      en: 'Small, repeatable habits change everything over the long run...',
    },
    imageUrl: '/images/mustafa-3.jpg',
    videoUrl: null,
    socialUrl: null,
    featured: false,
    createdAt: '2026-06-02T09:00:00Z',
  },
  {
    id: 's5',
    slug: 'push-day',
    type: 'image',
    category: 'fitness',
    title: { tr: 'İtiş Günü', en: 'Push Day' },
    excerpt: {
      tr: 'Göğüs, omuz ve triceps için yüksek hacimli bir gün.',
      en: 'A high-volume day for chest, shoulders and triceps.',
    },
    body: { tr: '', en: '' },
    imageUrl: '/images/mustafa-5.jpg',
    videoUrl: null,
    socialUrl: 'https://instagram.com',
    featured: false,
    createdAt: '2026-05-30T09:00:00Z',
  },
];

export const SAMPLE_SOCIAL: SocialItem[] = [
  {
    id: 'so1',
    imageUrl: '/images/mustafa-1.jpg',
    socialUrl: 'https://instagram.com',
    platform: 'instagram',
    caption: { tr: 'Antrenman günü', en: 'Training day' },
    createdAt: '2026-06-11T09:00:00Z',
  },
  {
    id: 'so2',
    imageUrl: '/images/mustafa-3.jpg',
    socialUrl: 'https://instagram.com',
    platform: 'instagram',
    caption: { tr: 'Form kontrolü', en: 'Form check' },
    createdAt: '2026-06-09T09:00:00Z',
  },
  {
    id: 'so3',
    imageUrl: '/images/mustafa-5.jpg',
    socialUrl: 'https://instagram.com',
    platform: 'instagram',
    caption: { tr: 'Sahne hazırlığı', en: 'Stage prep' },
    createdAt: '2026-06-07T09:00:00Z',
  },
  {
    id: 'so4',
    imageUrl: '/images/mustafa-4.jpg',
    socialUrl: 'https://instagram.com',
    platform: 'instagram',
    caption: { tr: 'Günlük disiplin', en: 'Everyday discipline' },
    createdAt: '2026-06-04T09:00:00Z',
  },
];

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: 'r1',
    category: 'smoothie',
    title: { tr: 'Yeşil Güç Smoothie', en: 'Green Power Smoothie' },
    description: {
      tr: 'Ispanak, muz, fıstık ezmesi ve whey ile antrenman sonrası toparlanma içeceği.',
      en: 'Spinach, banana, peanut butter and whey for a post-workout recovery hit.',
    },
    kcal: 320,
    protein: 28,
    timeMin: 5,
    imageUrl: null,
    youtubeUrl: 'https://www.youtube.com/watch?v=2vjPBrBU-TM',
    featured: true,
    createdAt: '2026-06-18T09:00:00Z',
  },
  {
    id: 'r2',
    category: 'highprotein',
    title: { tr: 'Acılı Tavuk & Pirinç Kasesi', en: 'Spicy Chicken & Rice Bowl' },
    description: {
      tr: 'Yüksek protein, düşük yağ. Meal-prep için ideal, 4 porsiyon.',
      en: 'High protein, low fat. Perfect for meal-prep, makes 4 portions.',
    },
    kcal: 540,
    protein: 46,
    timeMin: 25,
    imageUrl: null,
    youtubeUrl: 'https://www.youtube.com/watch?v=UBMk30rjy0o',
    featured: false,
    createdAt: '2026-06-16T09:00:00Z',
  },
  {
    id: 'r3',
    category: 'breakfast',
    title: { tr: 'Protein Yulaf Kasesi', en: 'Protein Overnight Oats' },
    description: {
      tr: 'Akşamdan hazırla, sabah enerjiyle başla. Yulaf, yoğurt, chia ve meyve.',
      en: 'Prep at night, wake up to fuel. Oats, yogurt, chia and berries.',
    },
    kcal: 410,
    protein: 32,
    timeMin: 10,
    imageUrl: null,
    youtubeUrl: null,
    featured: false,
    createdAt: '2026-06-14T09:00:00Z',
  },
  {
    id: 'r4',
    category: 'snack',
    title: { tr: 'Çikolatalı Protein Topları', en: 'Chocolate Protein Bites' },
    description: {
      tr: 'Şekersiz, taşınabilir atıştırmalık. Hurma, kakao ve fındık.',
      en: 'No added sugar, grab-and-go fuel. Dates, cacao and hazelnuts.',
    },
    kcal: 180,
    protein: 12,
    timeMin: 15,
    imageUrl: null,
    youtubeUrl: null,
    featured: false,
    createdAt: '2026-06-12T09:00:00Z',
  },
  {
    id: 'r5',
    category: 'smoothie',
    title: { tr: 'Yaban Mersinli Antioksidan', en: 'Blueberry Antioxidant Blend' },
    description: {
      tr: 'Yaban mersini, pancar ve keten tohumu — toparlanma ve odak için.',
      en: 'Blueberry, beetroot and flax — built for recovery and focus.',
    },
    kcal: 260,
    protein: 18,
    timeMin: 5,
    imageUrl: null,
    youtubeUrl: null,
    featured: false,
    createdAt: '2026-06-10T09:00:00Z',
  },
  {
    id: 'r6',
    category: 'highprotein',
    title: { tr: 'Somon & Tatlı Patates', en: 'Salmon & Sweet Potato' },
    description: {
      tr: 'Omega-3 ve yavaş karbonhidrat. Fırında 30 dakikada hazır.',
      en: 'Omega-3 and slow carbs. Oven-ready in 30 minutes.',
    },
    kcal: 600,
    protein: 44,
    timeMin: 30,
    imageUrl: null,
    youtubeUrl: null,
    featured: false,
    createdAt: '2026-06-08T09:00:00Z',
  },
];

export const SAMPLE_SETTINGS: SiteSettings = {
  whatsappUrl: 'https://wa.me/905555555555',
  instagramUrl: 'https://instagram.com',
  tiktokUrl: '',
  youtubeUrl: '',
  heroVideoUrl: '',
};
