import type { Locale } from '@/i18n/config';

const en = {
  title: 'Admin',
  login: 'Admin Login',
  google: 'Sign in with Google',
  notConfigured: 'Supabase is not configured. Add NEXT_PUBLIC_SUPABASE_* to your environment.',
  notAuthorized: 'This account is not authorized for admin.',
  signOut: 'Sign out',
  loading: 'Loading…',
  tabs: { posts: 'Posts', recipes: 'Recipes', members: 'Members', clients: 'Clients', social: 'Social Wall', settings: 'Settings' },
  saving: 'Saving…',
  save: 'Save',
  saved: 'Saved',
  add: 'Add',
  edit: 'Edit',
  remove: 'Delete',
  approve: 'Approve',
  unapprove: 'Unpublish',
  pending: 'Pending review',
  back: 'Back',
  cancel: 'Cancel',
  newPost: 'New post',
  newRecipe: 'New recipe',
  confirmDelete: 'Delete this item?',
  empty: 'Nothing yet.',
  fields: {
    slug: 'Slug (url)',
    type: 'Type',
    category: 'Category',
    titleTr: 'Title (TR)',
    titleEn: 'Title (EN)',
    excerptTr: 'Excerpt (TR)',
    excerptEn: 'Excerpt (EN)',
    bodyTr: 'Body (TR)',
    bodyEn: 'Body (EN)',
    descriptionTr: 'Description (TR)',
    descriptionEn: 'Description (EN)',
    kcal: 'Calories (kcal)',
    protein: 'Protein (g)',
    time: 'Time (min)',
    image: 'Image / thumbnail',
    video: 'Video URL (YouTube / Vimeo)',
    social: 'Social link (optional)',
    featured: 'Featured',
    published: 'Published',
    order: 'Order',
    caption: 'Caption',
    platform: 'Platform',
    pasteUrl: 'or paste an image URL',
    whatsapp: 'WhatsApp link',
    instagram: 'Instagram link',
    tiktok: 'TikTok link',
    youtube: 'YouTube link',
    heroVideo: 'Hero video URL (mp4)',
  },
  types: { video: 'Video', image: 'Photo', blog: 'Article' },
  categories: {
    fitness: 'Fitness',
    health: 'Health',
    lifestyle: 'LifeStyle',
    nutrition: 'Nutrition',
    mindset: 'Mindset',
    training: 'Training',
  },
  recipeCategories: {
    smoothie: 'Smoothies',
    highprotein: 'High-Protein',
    breakfast: 'Breakfast',
    snack: 'Snacks',
  },
};

const tr: typeof en = {
  title: 'Admin',
  login: 'Admin Girişi',
  google: 'Google ile giriş yap',
  notConfigured: 'Supabase yapılandırılmamış. Ortama NEXT_PUBLIC_SUPABASE_* anahtarlarını ekleyin.',
  notAuthorized: 'Bu hesap admin için yetkili değil.',
  signOut: 'Çıkış',
  loading: 'Yükleniyor…',
  tabs: { posts: 'Gönderiler', recipes: 'Tarifler', members: 'Üyeler', clients: 'Danışanlar', social: 'Sosyal Duvar', settings: 'Ayarlar' },
  saving: 'Kaydediliyor…',
  save: 'Kaydet',
  saved: 'Kaydedildi',
  add: 'Ekle',
  edit: 'Düzenle',
  remove: 'Sil',
  approve: 'Onayla',
  unapprove: 'Yayından kaldır',
  pending: 'Onay bekliyor',
  back: 'Geri',
  cancel: 'Vazgeç',
  newPost: 'Yeni gönderi',
  newRecipe: 'Yeni tarif',
  confirmDelete: 'Bu öğe silinsin mi?',
  empty: 'Henüz içerik yok.',
  fields: {
    slug: 'Slug (url)',
    type: 'Tür',
    category: 'Kategori',
    titleTr: 'Başlık (TR)',
    titleEn: 'Başlık (EN)',
    excerptTr: 'Özet (TR)',
    excerptEn: 'Özet (EN)',
    bodyTr: 'İçerik (TR)',
    bodyEn: 'İçerik (EN)',
    descriptionTr: 'Açıklama (TR)',
    descriptionEn: 'Açıklama (EN)',
    kcal: 'Kalori (kcal)',
    protein: 'Protein (g)',
    time: 'Süre (dk)',
    image: 'Görsel / kapak',
    video: 'Video adresi (YouTube / Vimeo)',
    social: 'Sosyal medya linki (opsiyonel)',
    featured: 'Öne çıkan',
    published: 'Yayında',
    order: 'Sıra',
    caption: 'Açıklama',
    platform: 'Platform',
    pasteUrl: 'veya bir görsel adresi yapıştır',
    whatsapp: 'WhatsApp linki',
    instagram: 'Instagram linki',
    tiktok: 'TikTok linki',
    youtube: 'YouTube linki',
    heroVideo: 'Hero video adresi (mp4)',
  },
  types: { video: 'Video', image: 'Fotoğraf', blog: 'Yazı' },
  categories: {
    fitness: 'Fitness',
    health: 'Sağlık',
    lifestyle: 'Yaşam Tarzı',
    nutrition: 'Beslenme',
    mindset: 'Motivasyon',
    training: 'Antrenman',
  },
  recipeCategories: {
    smoothie: 'Smoothie',
    highprotein: 'Yüksek Protein',
    breakfast: 'Kahvaltı',
    snack: 'Atıştırmalık',
  },
};

export type AdminLabels = typeof en;

export function getAdminLabels(locale: Locale): AdminLabels {
  return locale === 'tr' ? tr : en;
}
